# Generated by Django 4.2.7 on 2024-01-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='Core.subjects', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Core.themes', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('rightAnswer', models.CharField(max_length=100, verbose_name='Правильны(е) ответ(ы)')),
                ('answerOptions', models.CharField(max_length=300, verbose_name='Варианты ответов')),
                ('enteringLargeResponce', models.TextField(blank=True, verbose_name='Введите текст...')),
                ('enteringSmallResponce', models.CharField(max_length=100, verbose_name='Введите текст ...')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Core.tests', verbose_name='Вопрос')),
            ],
        ),
    ]
